name: Build Char Device

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential linux-headers-$(uname -r)

    - name: Build kernel module
      run: make
      working-directory: Drivers/char_device

    - name: Build test program
      run: gcc test_char_device.c -o test_char_device
      working-directory: Drivers/char_device
